# 第一阶段：构建环境
FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .

RUN apt-get update && apt-get install -y gcc zlib1g-dev && apt-get clean
RUN mkdir -p /root/.pip && \
    echo "[global]" > /root/.pip/pip.conf && \
    echo "index-url = https://pypi.tuna.tsinghua.edu.cn/simple" >> /root/.pip/pip.conf
RUN pip install uv
ENV UV_SYSTEM_PYTHON=1
RUN uv venv /opt/.venv
ENV VIRTUAL_ENV=/opt/.venv
ENV PATH="/opt/.venv/bin:$PATH"
RUN uv pip install --no-cache-dir torch==2.2.2+cpu --index-url https://download.pytorch.org/whl/cpu
RUN uv pip install --no-cache-dir -r requirements.txt



