from sqlalchemy import Column, Date, DateTime, Index, Integer, MetaData, Numeric, String, Table, text

metadata = MetaData()


t_ADMSN_INPAT_RFP = Table(
    'ADMSN_INPAT_RFP', metadata,
    Column('ORG_CODE', String(32, 'Chinese_PRC_BIN'), nullable=False, comment='医疗机构代码'),
    Column('PAT_ID', String(64, 'Chinese_PRC_BIN'), nullable=False, comment='患者ID'),
    Column('VISITING_SEQ_NO', String(64, 'Chinese_PRC_BIN'), nullable=False, comment='就诊流水号'),
    Column('EMR_NO', String(24, 'Chinese_PRC_BIN'), nullable=False, comment='疾病诊断编码'),
    Column('OUTPATIENT_NO', String(24, 'Chinese_PRC_BIN'), comment='门(急)诊号'),
    Column('PAT_NAME', String(64, 'Chinese_PRC_BIN'), nullable=False, comment='患者姓名'),
    Column('SEX_NAME', String(8, 'Chinese_PRC_BIN'), nullable=False, comment='性别名称'),
    Column('BIRTH_TIME', DateTime, nullable=False, comment='出生日期时间'),
    Column('BIRTH_DATE', Date, comment='出生日期'),
    Column('EMPLOYER_CODE', String(32, 'Chinese_PRC_BIN'), comment='工作单位编码'),
    Column('IDCARD_NO', String(20, 'Chinese_PRC_BIN'), nullable=False, comment='身份证件号码'),
    Column('CONTACTER', String(64, 'Chinese_PRC_BIN'), comment='联系人姓名'),
    Column('CONTACTER_PAT_REL_CODE', String(2, 'Chinese_PRC_BIN'), comment='联系人与患者的关系代码'),
    Column('CONTACTER_TEL_NO', String(16, 'Chinese_PRC_BIN'), comment='联系人电话号码'),
    Column('CONTACTER_ADDR', String(256, 'Chinese_PRC_BIN'), comment='联系人地址'),
    Column('INSUR_CERT_NO', String(32, 'Chinese_PRC_BIN'), comment='医保凭证号'),
    Column('MAIN_CARD_NO', String(32, 'Chinese_PRC_BIN'), comment='主要卡号'),
    Column('HEALTHCARD_TYPE_CODE', String(2, 'Chinese_PRC_BIN'), comment='就诊卡类型'),
    Column('SOCIAL_INSUR_CARD_NO', String(32, 'Chinese_PRC_BIN'), comment='社保卡号'),
    Column('OTHER_CARD_NO', String(32, 'Chinese_PRC_BIN'), comment='其他卡号'),
    Column('PAT_STATUS', String(1, 'Chinese_PRC_BIN'), nullable=False, comment='病人状态'),
    Column('PAT_TYPE_CODE', String(2, 'Chinese_PRC_BIN'), comment='患者类型代码'),
    Column('CURR_SEVERE_GRADE', String(2, 'Chinese_PRC_BIN'), nullable=False, comment='当前危重级别'),
    Column('MAIN_DIAG_CODE', String(32, 'Chinese_PRC_BIN'), nullable=False, comment='疾病诊断编码'),
    Column('ER_OBS_FLAG', String(1, 'Chinese_PRC_BIN'), nullable=False, comment='急观标志'),
    Column('BABY_FLAG', String(1, 'Chinese_PRC_BIN'), nullable=False, comment='婴儿标志'),
    Column('INSUR_CODE', String(32, 'Chinese_PRC_BIN'), nullable=False, comment='医疗保险类别代码'),
    Column('INSUR_FIXED_AMT', Numeric(14, 2), nullable=False, comment='医保定额'),
    Column('DEPT_CODE', String(32, 'Chinese_PRC_BIN'), nullable=False, comment='科室代码'),
    Column('WARD_CODE', String(32, 'Chinese_PRC_BIN'), nullable=False, comment='病区代码'),
    Column('DOC_ID', String(32, 'Chinese_PRC_BIN'), nullable=False, comment='医师编码'),
    Column('BED_NO', String(32, 'Chinese_PRC_BIN'), nullable=False, comment='床位号'),
    Column('NURSING_RANK_CODE', String(32, 'Chinese_PRC_BIN'), nullable=False, comment='护理等级代码'),
    Column('NURSING_RANK_NAME', String(128, 'Chinese_PRC_BIN'), nullable=False, comment='护理等级名称'),
    Column('DIET_CODE', String(32, 'Chinese_PRC_BIN'), comment='饮食代码'),
    Column('DIET_ORDER', String(128, 'Chinese_PRC_BIN'), comment='饮食医嘱'),
    Column('OPERATOR_ID', String(32, 'Chinese_PRC_BIN'), comment='操作员号'),
    Column('RECORD_TIME', DateTime, nullable=False, comment='记录日期时间'),
    Column('INPATIENT_SEVERE_GRADE', String(2, 'Chinese_PRC_BIN'), nullable=False, comment='入院危重级别'),
    Column('ADMISSION_WAY_CODE', String(2, 'Chinese_PRC_BIN'), nullable=False, comment='入院途径代码'),
    Column('DISC_WAY_CODE', String(2, 'Chinese_PRC_BIN'), nullable=False, comment='出院方式'),
    Column('INPATIENT_CNT', Integer, nullable=False, comment='住院次数(次)'),
    Column('ADMISSION_TIME', DateTime, nullable=False, comment='入院日期时间'),
    Column('IN_WARD_TIME', DateTime, nullable=False, comment='入区日期时间'),
    Column('DISC_TIME', DateTime, comment='出院日期时间'),
    Column('OUT_WARD_TIME', DateTime, comment='出区日期时间'),
    Column('DISC_DIAG_CODE', String(32, 'Chinese_PRC_BIN'), comment='出院诊断编码'),
    Column('DISC_DIAG_NAME', String(256, 'Chinese_PRC_BIN'), comment='出院诊断名称'),
    Column('INSUR_CENTER_NO', String(36, 'Chinese_PRC_BIN'), comment='医保中心编号'),
    Column('INSUR_DISCHARGE_TYPE_CODE', String(4, 'Chinese_PRC_BIN'), comment='医保出院类型'),
    Column('FOLLOW_UP_VISIT_PAT_FLAG', String(1, 'Chinese_PRC_BIN'), nullable=False, comment='随访病人标志'),
    Column('PAT_ON_LEAVE_DISCHARGE_FLAG', String(1, 'Chinese_PRC_BIN'), nullable=False, comment='病人请假出院标志'),
    Column('BABY_TRANS_BED_FLAG', String(1, 'Chinese_PRC_BIN'), nullable=False, comment='婴儿转床标志'),
    Column('CADRE_FLAG', String(1, 'Chinese_PRC_BIN'), nullable=False, comment='干保标志'),
    Column('CLINICAL_PATH_FLAG', String(1, 'Chinese_PRC_BIN'), nullable=False, comment='临床路径标志'),
    Column('OUT_WARD_CALLBACK_AUDIT_FLAG', String(1, 'Chinese_PRC_BIN'), nullable=False, comment='出区召回审核标志'),
    Column('OUT_WARD_CALLBACK_REASON', String(1000, 'Chinese_PRC_BIN'), comment='出区召回原因'),
    Column('EMR_SEAL_UP_FLAG', String(1, 'Chinese_PRC_BIN'), nullable=False, comment='病历封存标志'),
    Column('EMR_SEAL_UP_TIME', DateTime, comment='病历封存日期时间'),
    Column('EMR_ARCHIVE_FLAG', String(1, 'Chinese_PRC_BIN'), nullable=False, comment='病历归档标志'),
    Column('EMR_ARCHIVE_TIME', DateTime, comment='病历归档日期时间'),
    Column('OUTPAT_DIAG_DOC_ID', String(32, 'Chinese_PRC_BIN'), comment='门诊诊断医生'),
    Column('OUTPAT_DIAG_DOC_2ND_ID', String(32, 'Chinese_PRC_BIN'), comment='门诊诊断医生2'),
    Column('NURSING_GROUP_CODE', String(32, 'Chinese_PRC_BIN'), comment='护理组代码'),
    Column('MED_GROUP_CODE', String(32, 'Chinese_PRC_BIN'), comment='医疗组代码'),
    Column('WEIGHT', String(16, 'Chinese_PRC_BIN'), comment='体重(kg)'),
    Column('SINGLE_DISEASE_DIAG_CODE', String(32, 'Chinese_PRC_BIN'), comment='单病种诊断代码'),
    Column('NRCMS_CODE', String(20, 'Chinese_PRC_BIN'), comment='新农合编号'),
    Column('RESP_NURSING_ID', String(32, 'Chinese_PRC_BIN'), comment='责任护士编码'),
    Column('SUPDOC_ID', String(32, 'Chinese_PRC_BIN'), comment='上级医师编码'),
    Column('ACCOUNT_FLAG', String(1, 'Chinese_PRC_BIN'), nullable=False, comment='账户标志'),
    Column('GUARANTOR_NAME', String(64, 'Chinese_PRC_BIN'), comment='担保人'),
    Column('GUARANTEE_AMT', Numeric(14, 2), comment='担保金额'),
    Column('DEPOSIT_STOP_DRUG_LINE', Numeric(14, 2), comment='押金停药线'),
    Column('DEPOSIT_ALERT_LINE', Numeric(14, 2), comment='押金报警线'),
    Column('ACCOUNT_BALANCE', Numeric(14, 2), comment='账户余额'),
    Column('WHOLE_TOT_AMT', Numeric(14, 2), comment='统筹累计金额'),
    Column('NOTE', String(128, 'Chinese_PRC_BIN'), comment='备注'),
    Column('DATA_UPDATE_TIME', DateTime, nullable=False, comment='数据更新日期时间'),
    Column('SYSTEM_FLAG', String(50, 'Chinese_PRC_BIN'), nullable=False, comment='系统标志'),
    Column('DATA_STATUS', String(10, 'Chinese_PRC_BIN'), nullable=False, comment='数据状态'),
    Column('ORG_NAME', String(128, 'Chinese_PRC_BIN'), nullable=False, server_default=text("(' ')")),
    Column('MAIN_DIAG_NAME', String(256, 'Chinese_PRC_BIN'), nullable=False, server_default=text("(' ')")),
    Column('DEPT_NAME', String(64, 'Chinese_PRC_BIN'), nullable=False, server_default=text("(' ')")),
    Column('ADMISSION_DEPT_CODE', String(32, 'Chinese_PRC_BIN'), nullable=False, server_default=text("(' ')")),
    Column('ADMISSION_DEPT_NAME', String(64, 'Chinese_PRC_BIN'), nullable=False, server_default=text("(' ')")),
    Column('DISC_DEPT_CODE', String(32, 'Chinese_PRC_BIN'), nullable=False, server_default=text("(' ')")),
    Column('DISC_DEPT_NAME', String(64, 'Chinese_PRC_BIN'), nullable=False, server_default=text("(' ')")),
    Column('WARD_NAME', String(64, 'Chinese_PRC_BIN'), nullable=False, server_default=text("(' ')")),
    Column('DOC_NAME', String(64, 'Chinese_PRC_BIN'), nullable=False, server_default=text("(' ')")),
    Column('OPERATOR_NAME', String(64, 'Chinese_PRC_BIN')),
    Column('OUTPAT_DIAG_DOC_NAME', String(64, 'Chinese_PRC_BIN')),
    Column('OUTPAT_DIAG_DOC_2ND_NAME', String(64, 'Chinese_PRC_BIN')),
    Column('RESP_NURSINGNAME', String(64, 'Chinese_PRC_BIN')),
    Column('SUPDOC_NAME', String(64, 'Chinese_PRC_BIN')),
    Column('SEX_CODE', String(32, 'Chinese_PRC_BIN'), nullable=False, server_default=text("(' ')")),
    Column('PREMIUM_NURSE_FLAG', String(128, 'Chinese_PRC_BIN')),
    Index('PK_ADMSN_INPAT_RFP', 'ORG_CODE', 'VISITING_SEQ_NO', 'SYSTEM_FLAG', unique=True)
)
